services:
  - type: web
    name: noir-collect-api
    env: node
    rootDir: backend
    plan: free
    buildCommand: npm install
    startCommand: npm run migrate && node src/index.js
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 4000
      - key: DATABASE_URL
        fromDatabase:
          name: noir-collect-db
          property: connectionString
      - key: COMICVINE_API_KEY
        sync: false
      - key: GOOGLE_BOOKS_API_KEY
        sync: false
      - key: OPEN_LIBRARY_API
        value: https://openlibrary.org
      - key: METRON_BASE
        value: https://metron.cloud/api
      - key: METRON_USERNAME
        sync: false
      - key: METRON_PASSWORD
        sync: false
      - key: AUTH_TOKEN
        sync: false

databases:
  - name: noir-collect-db
    plan: free
